name: Test Numba on macOS Intel

on:
  workflow_dispatch:

jobs:
  test-numba:
    runs-on: macos-15-intel
    steps:
      - name: Install numba
        run: pip install numba

      - name: Verify numba import
        run: 
          |
          python -c "import numba; print(f'numba {numba.__version__} installed successfully')"
          numba -s

  test-numba-062:
    runs-on: macos-15-intel
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install numba
        run: PIP_ONLY_BINARY=":all:" pip install numba

      - name: Verify numba import
        run: 
          |
          python -c "import numba; print(f'numba {numba.__version__} installed successfully')"
          numba -s